language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env: DEPS=dev
    - php: 5.5
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: 7.0
      env: SYMFONY_VERSION=2.7.*
    - php: 7.0
      env: SYMFONY_VERSION=2.8.*

before_install:
  - phpenv config-rm xdebug.ini || true
  - composer self-update
  - if [ "$DEPS" = "dev" ]; then perl -pi -e 's/^}$/,"minimum-stability":"dev"}/' composer.json; fi
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require symfony/symfony:${SYMFONY_VERSION} --no-update; fi

install: composer update --prefer-dist $COMPOSER_FLAGS
